// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Rj5n2mRTa7c0-GoB23chiS7MrWTB-Pg',
    appId: '1:797029975098:web:ba017ae96e841e4b146103',
    messagingSenderId: '797029975098',
    projectId: 'friutappdesignwithfirebasedata',
    authDomain: 'friutappdesignwithfirebasedata.firebaseapp.com',
    storageBucket: 'friutappdesignwithfirebasedata.appspot.com',
    measurementId: 'G-B6ZH7CY9FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbJd_JHm2l9JomoO0bM1vFmn9HCBMKb4',
    appId: '1:797029975098:android:ef9d67b5ae35d007146103',
    messagingSenderId: '797029975098',
    projectId: 'friutappdesignwithfirebasedata',
    storageBucket: 'friutappdesignwithfirebasedata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QoVtMRyKdvUo3WQBC5AZxnopMIBVnWY',
    appId: '1:797029975098:ios:981199c312a87016146103',
    messagingSenderId: '797029975098',
    projectId: 'friutappdesignwithfirebasedata',
    storageBucket: 'friutappdesignwithfirebasedata.appspot.com',
    iosClientId: '797029975098-tvcd4098j5mifhfvv2ugj3hds6l4h6uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitproject',
  );
}
